# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d9fdfc131b9780df9082ebdcfb41a9a4de4204cc74d5952f241d53b14a8ce69860cb7f6d42b4377abba2b2d61592a6faf5542ea9219dcfbe4fabb503faedf3

test:
  secret_key_base: f03c7ccd3a89c42727bebfac3e0811ab80be1152f898dd176c1906521d002dfa53abb8315a8f25dc8793e9d2f0b969c073a38e722bff69f44e70d63777ffc7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
